# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cert_subj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OU', models.CharField(blank=True, max_length=1000, null=True, verbose_name='OU')),
                ('C', models.CharField(blank=True, max_length=1000, null=True, verbose_name='C')),
                ('O', models.CharField(blank=True, max_length=1000, null=True, verbose_name='O')),
                ('L', models.CharField(blank=True, max_length=1000, null=True, verbose_name='L')),
                ('ST', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ST')),
                ('CN', models.CharField(blank=True, max_length=1000, null=True, verbose_name='CN')),
                ('street', models.CharField(blank=True, max_length=1000, null=True, verbose_name='street')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='title')),
                ('emailAddress', models.CharField(blank=True, max_length=1000, null=True, verbose_name='emailAddress')),
                ('serial', models.CharField(blank=True, max_length=1000, null=True, verbose_name='serial')),
                ('notafter', models.DateTimeField(blank=True, null=True, verbose_name='notafter')),
                ('notbefore', models.DateTimeField(blank=True, null=True, verbose_name='notbefore')),
                ('dt_create', models.DateTimeField(auto_now=True, verbose_name='creationdate')),
                ('dt_update', models.DateTimeField(auto_now_add=True, verbose_name='updatedate')),
            ],
        ),
    ]
