# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertCat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert_subj',
            name='dt_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='cert_subj',
            name='dt_update',
            field=models.DateTimeField(auto_now=True, verbose_name='update date'),
        ),
        migrations.AlterField(
            model_name='cert_subj',
            name='emailAddress',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='cert_subj',
            name='notafter',
            field=models.DateTimeField(blank=True, null=True, verbose_name='not after'),
        ),
        migrations.AlterField(
            model_name='cert_subj',
            name='notbefore',
            field=models.DateTimeField(blank=True, null=True, verbose_name='not before'),
        ),
    ]
